include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Uncomment to disable the `avoid_print` rule
    # avoid_print: false  
    # Uncomment to enable the `prefer_single_quotes` rule
    # prefer_single_quotes: true  
