name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.0.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/rgb_cube_data.json
    - assets/rgb_cube_3d.html
